# Generated by Django 5.0.4 on 2024-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_designs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='state',
        ),
    ]
