# Generated by Django 5.0.3 on 2024-04-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_designs', '0002_alter_plant_options_plant_variety_alter_plant_genus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
