# Generated by Django 5.0.4 on 2024-12-02 21:55

from django.db import migrations

import uuid


def set_uuids(apps, schema_editor):
    models = [
        "Plant",
        "PlantImage",
        "PlantImageKind",
        "PlantLog",
        "PlantLogKind",
        "Zone",
        "ZoneKind",
        # "Family",
        # "FamilyCommonName",
        # "Genus",
        # "GenusCommonName",
        # "Species",
        # "SpeciesCommonName",
        # "SpeciesVariety",
    ]

    for model_name in models:
        Model = apps.get_model("forest_designs", model_name)
        for instance in Model.objects.all():
            instance.uuid = uuid.uuid4()
            instance.save(update_fields=["uuid"])


def reverse_uuids(apps, schema_editor):
    pass  # Cannot meaningfully reverse UUID assignment


class Migration(migrations.Migration):
    dependencies = [
        (
            "forest_designs",
            "0003_plant_uuid_plantimage_uuid_plantimagekind_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(set_uuids, reverse_uuids),
    ]
