# Generated by Django 5.0.4 on 2024-12-21 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forest_designs", "0003_plant_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="plant",
            field=models.ForeignKey(
                db_column="plant_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="forest_designs.plant",
                to_field="uuid",
            ),
        ),
    ]
