# Generated by Django 5.0.4 on 2024-05-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_designs', '0003_remove_plant_project_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImageKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'plant image type',
                'verbose_name_plural': 'plant image types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantLogKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'plant log type',
                'verbose_name_plural': 'plant log types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('image', models.ImageField(upload_to='plant_images')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forest_designs.plant')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forest_designs.plantimagekind')),
            ],
            options={
                'verbose_name': 'plant image',
                'verbose_name_plural': 'plant images',
                'ordering': ('plant', '-date'),
            },
        ),
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the log entry.')),
                ('notes', models.TextField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forest_designs.plant')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forest_designs.plantlogkind')),
            ],
            options={
                'verbose_name': 'plant log',
                'verbose_name_plural': 'plant logs',
                'ordering': ['-date'],
            },
        ),
    ]
