# Generated by Django 5.0.4 on 2024-05-25 17:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "forest_designs",
            "0004_plantimagekind_plantlogkind_plant_notes_plantimage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "zone type",
                "verbose_name_plural": "zone types",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "area",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="area"
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forest_designs.zonekind",
                    ),
                ),
            ],
            options={
                "verbose_name": "zone",
                "verbose_name_plural": "zones",
                "ordering": ["name"],
            },
        ),
    ]
