# Generated by Django 5.0.4 on 2024-05-25 18:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_designs', '0005_zonekind_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimagekind',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plantlogkind',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='zonekind',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='plant_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of the log entry.', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='notes',
            field=models.TextField(verbose_name='notes'),
        ),
    ]
