# Generated by Django 5.0.3 on 2024-04-15 14:29
from django.db import migrations


def create_initial_growth_habits(apps, schema_editor):
    GrowthHabit = apps.get_model("species_data", "GrowthHabit")
    growth_habits = [
        {
            "name": "Tree",
            "description": "A woody perennial plant with a single main stem or trunk.",
        },
        {
            "name": "Shrub",
            "description": "A woody plant with multiple stems and shorter height than a tree.",
        },
        {"name": "Herb", "description": "A non-woody plant with soft, green stems."},
        {
            "name": "Vine",
            "description": "A climbing or trailing plant with long, slender stems.",
        },
        {
            "name": "Grass",
            "description": "A monocotyledonous plant with narrow leaves and hollow stems.",
        },
        {"name": "Fern", "description": "A flowerless, spore-bearing vascular plant."},
        {
            "name": "Moss",
            "description": "A small, non-vascular plant that grows in dense green clumps.",
        },
    ]
    for habit in growth_habits:
        GrowthHabit.objects.create(name=habit["name"], description=habit["description"])


class Migration(migrations.Migration):
    dependencies = [
        ("species_data", "0002_climate_zones"),
    ]
    operations = [
        migrations.RunPython(create_initial_growth_habits),
    ]
