# Generated by Django 5.0.4 on 2024-05-31 16:22

import django.core.validators
import django.db.models.deletion
import species_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0003_soil_preference_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropagationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of soil preference.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'propagation method',
                'verbose_name_plural': 'propagation methods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='humanusethroughbase',
            name='source',
        ),
        migrations.RenameField(
            model_name='speciesproperties',
            old_name='soil_preference',
            new_name='soil_preferences',
        ),
        migrations.CreateModel(
            name='SpeciesPropagationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', species_data.fields.ConfidenceField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='confidence')),
                ('propagation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_data.propagationmethod')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_data.source')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_data.speciesproperties')),
            ],
            options={
                'abstract': False,
                'unique_together': {('species', 'propagation_method')},
            },
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='propagation_methods',
            field=models.ManyToManyField(through='species_data.SpeciesPropagationMethod', to='species_data.propagationmethod'),
        ),
        migrations.DeleteModel(
            name='EcologicalRoleThroughBase',
        ),
        migrations.DeleteModel(
            name='HumanUseThroughBase',
        ),
    ]
