# Generated by Django 5.0.4 on 2024-12-09 15:10

import django.core.validators
import django.db.models.deletion
import species_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0004_propagation_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesproperties',
            name='precipitation_confidence',
            field=species_data.fields.ConfidenceField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='%(parent_verbose_name)s confidence'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='precipitation_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='precipitation_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='precipitation_source',
            field=species_data.fields.SourceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='precipitation_typical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='temperature_confidence',
            field=species_data.fields.ConfidenceField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='%(parent_verbose_name)s confidence'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='temperature_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='temperature_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='temperature_source',
            field=species_data.fields.SourceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='temperature_typical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
    ]
