# Generated by Django 5.0.4 on 2024-12-22 12:38

import species_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0004_propagation_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesclimatezone',
            name='source',
        ),
        migrations.RemoveField(
            model_name='speciesecologicalrole',
            name='source',
        ),
        migrations.RemoveField(
            model_name='speciesgrowthhabit',
            name='source',
        ),
        migrations.RemoveField(
            model_name='specieshumanuse',
            name='source',
        ),
        migrations.RemoveField(
            model_name='speciespropagationmethod',
            name='source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='height_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='lifetime_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='precipitation_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='production_peak_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='production_start_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='soil_acidity_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='sun_hours_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='temperature_source',
        ),
        migrations.RemoveField(
            model_name='speciesproperties',
            name='width_source',
        ),
        migrations.RemoveField(
            model_name='speciessoilpreference',
            name='source',
        ),
        migrations.AddField(
            model_name='speciesclimatezone',
            name='sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='speciesecologicalrole',
            name='sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='speciesgrowthhabit',
            name='sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='specieshumanuse',
            name='sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='speciespropagationmethod',
            name='sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='height_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='lifetime_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='precipitation_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='production_peak_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='production_start_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='soil_acidity_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='sun_hours_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='temperature_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='width_sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciessoilpreference',
            name='sources',
            field=species_data.fields.SourcesField(blank=True, related_name='+', to='species_data.source', verbose_name='sources'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
