# Generated by Django 5.0.4 on 2024-06-02 16:16

from django.db import migrations
from django.template.defaultfilters import slugify


def update_slug_climate_zones(apps, schema_editor):
    ClimateZone = apps.get_model("species_data", "ClimateZone")

    for obj in ClimateZone.objects.all():
        obj.slug = slugify(obj.name)
        obj.full_clean()
        obj.save()


def update_slug_initial_growth_habits(apps, schema_editor):
    GrowthHabit = apps.get_model("species_data", "GrowthHabit")

    for obj in GrowthHabit.objects.all():
        obj.slug = slugify(obj.name)
        obj.full_clean()
        obj.save()


def update_slug_human_uses(apps, schema_editor):
    HumanUse = apps.get_model("species_data", "HumanUse")

    for obj in HumanUse.objects.all():
        obj.slug = slugify(obj.name)
        obj.full_clean()
        obj.save()


def update_slug_ecological_roles(apps, schema_editor):
    EcologicalRole = apps.get_model("species_data", "EcologicalRole")

    for obj in EcologicalRole.objects.all():
        obj.slug = slugify(obj.name)
        obj.full_clean()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("species_data", "0005_propagation_methods"),
    ]

    operations = [
        migrations.RunPython(update_slug_climate_zones),
        migrations.RunPython(update_slug_initial_growth_habits),
        migrations.RunPython(update_slug_human_uses),
        migrations.RunPython(update_slug_ecological_roles),
    ]
