# Generated by Django 5.0.4 on 2024-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0005_ecological_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanuse',
            options={'ordering': ('use_type', 'name'), 'verbose_name': 'human use', 'verbose_name_plural': 'human uses'},
        ),
        migrations.AlterField(
            model_name='climatezone',
            name='heat_level',
            field=models.CharField(blank=True, choices=[('h', 'h: Hot arid'), ('k', 'k: Cold arid'), ('a', 'a: Hot summer'), ('b', 'b: Warm summer'), ('c', 'c: Cool summer'), ('d', 'd: Very cold winter'), ('T', 'T: Tundra'), ('F', 'F: Ice cap')], max_length=1, null=True, verbose_name='heat level'),
        ),
        migrations.AlterField(
            model_name='climatezone',
            name='main_group',
            field=models.CharField(choices=[('A', 'A: Tropical'), ('B', 'B: Dry'), ('C', 'C: Temperate'), ('D', 'D: Continental'), ('E', 'E: Polar')], max_length=1, verbose_name='main group'),
        ),
    ]
