# Generated by Django 5.0.4 on 2024-05-18 16:29

from django.db import migrations, models
from django.template.defaultfilters import slugify


def set_slugs(apps, schema_editor):
    model_names = [
        "ClimateZone",
        "EcologicalRole",
        "GrowthHabit",
        "HumanUse",
        "LightPreference",
        "SoilPreference",
    ]
    models = [apps.get_model("species_data", n) for n in model_names]

    for model in models:
        for instance in model.objects.all():
            instance.slug = slugify(instance.name)
            instance.save()


class Migration(migrations.Migration):
    replaces = [
        ("species_data", "0007_climatezone_slug_ecologicalrole_slug_and_more"),
        ("species_data", "0008_slug_from_name"),
        ("species_data", "0009_alter_climatezone_name_alter_climatezone_slug_and_more"),
    ]

    dependencies = [
        (
            "species_data",
            "0006_alter_humanuse_options_alter_climatezone_heat_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="climatezone",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="ecologicalrole",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="growthhabit",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="humanuse",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="lightpreference",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="soilpreference",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.RunPython(
            code=set_slugs,
        ),
        migrations.AlterField(
            model_name="climatezone",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="climatezone",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="ecologicalrole",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="ecologicalrole",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="growthhabit",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="growthhabit",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="humanuse",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="humanuse",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="lightpreference",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="lightpreference",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="soilpreference",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="soilpreference",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
    ]
