# Generated by Django 5.0.4 on 2024-05-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species_data", "0011_alter_source_url_alter_speciesproperties_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciesproperties",
            name="species",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="plant_species.species"
            ),
        ),
    ]
