# Generated by Django 5.0.4 on 2024-05-18 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("species_data", "0012_alter_speciesproperties_species"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="growthhabitthroughbase",
            name="source",
        ),
        migrations.RemoveField(
            model_name="lightpreferencethroughbase",
            name="source",
        ),
        migrations.RemoveField(
            model_name="soilpreferencethroughbase",
            name="source",
        ),
        migrations.AlterUniqueTogether(
            name="speciesclimatezone",
            unique_together={("species", "climate_zone")},
        ),
        migrations.AlterUniqueTogether(
            name="speciesecologicalrole",
            unique_together={("species", "ecological_role")},
        ),
        migrations.AlterUniqueTogether(
            name="speciesgrowthhabit",
            unique_together={("species", "growth_habit")},
        ),
        migrations.AlterUniqueTogether(
            name="specieshumanuse",
            unique_together={("species", "human_use")},
        ),
        migrations.AlterUniqueTogether(
            name="specieslightpreference",
            unique_together={("species", "light_preference")},
        ),
        migrations.AlterUniqueTogether(
            name="speciessoilpreference",
            unique_together={("species", "soil_texture")},
        ),
        migrations.DeleteModel(
            name="ClimateZoneThroughBase",
        ),
        migrations.DeleteModel(
            name="GrowthHabitThroughBase",
        ),
        migrations.DeleteModel(
            name="LightPreferenceThroughBase",
        ),
        migrations.DeleteModel(
            name="SoilPreferenceThroughBase",
        ),
    ]
