# Generated by Django 5.0.4 on 2024-05-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0013_remove_growthhabitthroughbase_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesproperties',
            name='height_maximum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='height_minimum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='height_typical',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='soil_acidity_maximum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='soil_acidity_minimum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='soil_acidity_typical',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='width_maximum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='width_minimum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='width_typical',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
    ]
