# Generated by Django 5.0.4 on 2024-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0014_alter_speciesproperties_height_maximum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
