# Generated by Django 5.0.4 on 2024-05-19 11:25

import django.core.validators
import django.db.models.deletion
import species_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_data', '0015_alter_sourcetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesproperties',
            name='sun_hours_confidence',
            field=species_data.fields.ConfidenceField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='%(parent_verbose_name)s confidence'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='sun_hours_maximum',
            field=models.DurationField(blank=True, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='sun_hours_minimum',
            field=models.DurationField(blank=True, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='sun_hours_source',
            field=species_data.fields.SourceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='species_data.source', verbose_name='%(parent_verbose_name)s source'),
        ),
        migrations.AddField(
            model_name='speciesproperties',
            name='sun_hours_typical',
            field=models.DurationField(blank=True, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
    ]
