# Generated by Django 5.0.4 on 2024-05-19 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("species_data", "0016_speciesproperties_sun_hours_confidence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speciesproperties",
            name="light_preference",
        ),
        migrations.AlterUniqueTogether(
            name="specieslightpreference",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="specieslightpreference",
            name="light_preference",
        ),
        migrations.RemoveField(
            model_name="specieslightpreference",
            name="species",
        ),
        migrations.RemoveField(
            model_name="specieslightpreference",
            name="source",
        ),
        migrations.DeleteModel(
            name="SpeciesLightPreference",
        ),
        migrations.DeleteModel(
            name="LightPreference",
        ),
    ]
