# Generated by Django 5.0.4 on 2024-05-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_species', '0001_initial'),
        ('species_data', '0010_alter_climatezone_slug_alter_ecologicalrole_slug_and_more_squashed_0017_remove_speciesproperties_light_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesproperties',
            name='height_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='height_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='height_typical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='soil_acidity_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='soil_acidity_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='soil_acidity_typical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='species',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='plant_species.species'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='width_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s maximum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='width_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s minimum'),
        ),
        migrations.AlterField(
            model_name='speciesproperties',
            name='width_typical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%(parent_verbose_name)s typical'),
        ),
    ]
