# Generated by Django 5.0.3 on 2024-04-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255, unique=True, verbose_name='latin name')),
                ('gbif_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usageKey')),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255, unique=True, verbose_name='latin name')),
                ('gbif_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usageKey')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genera', to='plant_species.family')),
            ],
            options={
                'verbose_name': 'genus',
                'verbose_name_plural': 'genera',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255, unique=True, verbose_name='latin name')),
                ('gbif_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usageKey')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species', to='plant_species.genus')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='FamilyCommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Portuguese'), ('nl', 'Dutch'), ('en', 'English')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='common name')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default name for language.', verbose_name='default')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='plant_species.family')),
            ],
            options={
                'verbose_name': 'common name',
                'verbose_name_plural': 'common names',
                'ordering': ['language', '-is_default', 'name'],
                'abstract': False,
                'unique_together': {('family', 'language', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GenusCommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Portuguese'), ('nl', 'Dutch'), ('en', 'English')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='common name')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default name for language.', verbose_name='default')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='plant_species.genus')),
            ],
            options={
                'verbose_name': 'common name',
                'verbose_name_plural': 'common names',
                'ordering': ['language', '-is_default', 'name'],
                'abstract': False,
                'unique_together': {('genus', 'language', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesCommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Portuguese'), ('nl', 'Dutch'), ('en', 'English')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='common name')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default name for language.', verbose_name='default')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='plant_species.species')),
            ],
            options={
                'verbose_name': 'common name',
                'verbose_name_plural': 'common names',
                'ordering': ['language', '-is_default', 'name'],
                'abstract': False,
                'unique_together': {('species', 'language', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='variety name')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='plant_species.species')),
            ],
            options={
                'verbose_name': 'variety',
                'verbose_name_plural': 'varieties',
                'ordering': ['species__latin_name', 'name'],
                'unique_together': {('species', 'name')},
            },
        ),
    ]
