# Generated by Django 5.0.3 on 2024-04-07 08:40

import django_advance_thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_species", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="plant_species/images/"
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="image_large",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="plant_species/images/large/"
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="image_thumbnail",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="plant_species/images/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="plant_species/images/"
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="image_large",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="plant_species/images/large/"
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="image_thumbnail",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="plant_species/images/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="plant_species/images/"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="image_large",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="plant_species/images/large/"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="image_thumbnail",
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="plant_species/images/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="gbif_id",
            field=models.IntegerField(
                editable=False, unique=True, verbose_name="GBIF usageKey"
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="gbif_id",
            field=models.IntegerField(
                editable=False, unique=True, verbose_name="GBIF usageKey"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="gbif_id",
            field=models.IntegerField(
                editable=False, unique=True, verbose_name="GBIF usageKey"
            ),
        ),
    ]
