# Generated by Django 5.0.3 on 2024-04-07 11:14

import django_advance_thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_species', '0002_family_image_family_image_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='genus',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='family',
            name='image_large',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, editable=False, null=True, upload_to='plant_species/images/large/'),
        ),
        migrations.AlterField(
            model_name='family',
            name='image_thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, editable=False, null=True, upload_to='plant_species/images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='image_large',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, editable=False, null=True, upload_to='plant_species/images/large/'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='image_thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, editable=False, null=True, upload_to='plant_species/images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image_large',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, editable=False, null=True, upload_to='plant_species/images/large/'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image_thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, editable=False, null=True, upload_to='plant_species/images/thumbnails/'),
        ),
    ]
