# Generated by Django 5.0.3 on 2024-04-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_species', '0003_family_description_genus_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['latin_name'], 'verbose_name': 'family', 'verbose_name_plural': 'families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['latin_name'], 'verbose_name': 'genus', 'verbose_name_plural': 'genera'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['latin_name'], 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
    ]
