# Generated by Django 5.0.4 on 2024-05-18 16:16

from django.db import migrations, models
from django.template.defaultfilters import slugify


def set_slugs(apps, schema_editor):
    Family = apps.get_model("plant_species", "Family")
    Genus = apps.get_model("plant_species", "Genus")
    Species = apps.get_model("plant_species", "Species")

    for model in (Family, Genus, Species):
        for instance in model.objects.all():
            instance.slug = slugify(instance.latin_name)
            instance.save()


class Migration(migrations.Migration):
    replaces = [
        ("plant_species", "0005_family_slug_genus_slug_species_slug"),
        ("plant_species", "0006_slug_from_name"),
        ("plant_species", "0007_alter_family_slug_alter_genus_slug_and_more"),
        ("plant_species", "0008_alter_family_latin_name_alter_family_slug_and_more"),
    ]

    dependencies = [
        ("plant_species", "0004_alter_family_options_alter_genus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
        migrations.RunPython(
            code=set_slugs,
        ),
        migrations.AlterField(
            model_name="family",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="latin name"
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="genus",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="latin name"
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="species",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="latin name"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
    ]
