# Generated by Django 5.0.3 on 2024-04-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycommonname',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as default name for language.', verbose_name='default'),
        ),
        migrations.AddField(
            model_name='genuscommonname',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as default name for language.', verbose_name='default'),
        ),
        migrations.AddField(
            model_name='speciescommonname',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as default name for language.', verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='family',
            name='gbif_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usageKey'),
        ),
        migrations.AlterField(
            model_name='familycommonname',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='species.family'),
        ),
        migrations.AlterField(
            model_name='familycommonname',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('nl', 'Dutch'), ('en', 'English')], max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='gbif_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usageKey'),
        ),
        migrations.AlterField(
            model_name='genuscommonname',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='species.genus'),
        ),
        migrations.AlterField(
            model_name='genuscommonname',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('nl', 'Dutch'), ('en', 'English')], max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gbif_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usageKey'),
        ),
        migrations.AlterField(
            model_name='speciescommonname',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('nl', 'Dutch'), ('en', 'English')], max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='speciescommonname',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='species.species'),
        ),
    ]
