# Generated by Django 5.0.3 on 2024-04-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_familycommonname_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familycommonname',
            options={'ordering': ['language', '-is_default', 'name'], 'verbose_name': 'common name', 'verbose_name_plural': 'common names'},
        ),
        migrations.AlterModelOptions(
            name='genuscommonname',
            options={'ordering': ['language', '-is_default', 'name'], 'verbose_name': 'common name', 'verbose_name_plural': 'common names'},
        ),
        migrations.AlterModelOptions(
            name='speciescommonname',
            options={'ordering': ['language', '-is_default', 'name'], 'verbose_name': 'common name', 'verbose_name_plural': 'common names'},
        ),
    ]
