# Generated by Django 5.0.3 on 2024-04-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_alter_familycommonname_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variety',
            new_name='SpeciesVariety',
        ),
    ]
